export const SESSION_CONFIGURATION = Symbol('SESSION_CONFIGURATION');
export const SESSION_MIDDLEWARE = Symbol('SESSION_MIDDLEWARE');
export const SESSION_ABSOLUTE_EXPIRY_MIDDLEWARE = Symbol(
  'SESSION_ABSOLUTE_EXPIRY_MIDDLEWARE',
);
