export {
  assertConfigurationConsistency,
  assertProductTransition,
  assertSingleFulfillmentClassification,
  assertVariantTransition,
  canonicalComparison,
  CATALOG_LIMITS,
  CatalogRuleError,
  combinationKey,
  normalizeSku,
  normalizeSlug,
  optionalText,
  requiredText,
  validateProductText,
  type FulfillmentClassification,
  type ProductStatus,
  type VariantStatus,
} from './catalog-rules';
